app:
  exchange:
    api_key: '%env(EXCHANGE_API_KEY)%'
    api_secret: '%env(EXCHANGE_API_SECRET)%'
    ladder_size: '%env(int:EXCHANGE_LADDER_SIZE)%'
    api_debugging_enabled: '%env(bool:EXCHANGE_API_DEBUGGING_ENABLED)%'
    portfolio_loss_threshold: '%env(float:PORTFOLIO_LOSS_THRESHOLD)%'
    stop_loss_risk_percentage: '%env(float:STOP_LOSS_RISK_PERCENTAGE)%'
