doctrine:
  dbal:
    # configure these for your database server
    driver: "pdo_pgsql"
    server_version: "11.5"
    charset: UTF-8
    url: "%env(resolve:DATABASE_URL)%"
  orm:
    auto_generate_proxy_classes: "%kernel.debug%"
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    metadata_cache_driver:
      type: redis
      host: "%env(REDIS_HOST)%"
      port: "%env(int:REDIS_PORT)%"
      database: 1
    query_cache_driver:
      type: redis
      host: "%env(REDIS_HOST)%"
      port: "%env(int:REDIS_PORT)%"
      database: 1
    result_cache_driver:
      type: redis
      host: "%env(REDIS_HOST)%"
      port: "%env(int:REDIS_PORT)%"
      database: 1
    mappings:
      App:
        is_bundle: false
        type: yml
        dir: "%kernel.project_dir%/config/doctrine"
        prefix: 'App\Model'
