framework:
  messenger:
    # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
    # failure_transport: failed

    transports:
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        retry_strategy:
          max_retries: 0
      sync:
        dsn: 'sync://'
        retry_strategy:
          max_retries: 0

    routing:
      'App\Bus\Message\AsyncMessageInterface': async

    default_bus: command.bus
    buses:
      command.bus:
        middleware:
          - validation
          - doctrine_transaction
          - doctrine_ping_connection
      query.bus:
        middleware:
          - validation
          - app.bus.middleware.cache
      event.bus:
        default_middleware: allow_no_handlers
        middleware:
          - validation
          - doctrine_ping_connection
