version: '3'
volumes:
  data-mysql:
    driver: local
services:
  php-fpm:
    build:
      context: .
      dockerfile: .docker/backend/Dockerfile
    restart: always
    env_file:
      - .env.local
    depends_on:
      - db
  stream-processor:
    build:
      context: .
      dockerfile: .docker/backend/Dockerfile
    restart: always
    command: ["php", "/app/bin/console", "app:user-stream:process", "-vvv"]
    env_file:
      - .env.local
    depends_on:
      - db
  webserver:
    build:
      context: .
      dockerfile: .docker/frontend/Dockerfile
    restart: always
    depends_on:
      - php-fpm
    ports:
      - 8080:80
  worker:
    build:
      context: .
      dockerfile: .docker/backend/Dockerfile
    restart: always
    command: ["php", "/app/bin/console", "messenger:consume", "async", "-vvv"]
    env_file:
      - .env.local
    depends_on:
      - db
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env.local
    volumes:
      - "data-mysql:/var/lib/mysql"
