version: "3"
services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - "./.docker/development/data/postgres:/var/lib/postgresql/data:delegated"
  queue:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./.docker/development/data/rabbitmq:/var/lib/rabbitmq:delegated"
