entrypoint:
  path: /{vueRouting}
  requirements:
    vueRouting: ^(?!api).+
  defaults:
    vueRouting: ~
  controller: app.controller.single_page_app::index

api_get_symbol:
  path: /api/v1/symbol/{strSymbol}
  controller: app.controller.symbol_controller::getSymbol

api_get_symbols:
  path: /api/v1/symbol
  controller: app.controller.symbol_controller::getSymbols

api_get_trades:
  path: /api/v1/trade
  controller: app.controller.trade_controller::getActiveTrades

api_get_account_value:
  path: /api/v1/account/value
  controller: app.controller.account_controller::getAccountValue
