parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Model,Migrations,Tests,Kernel.php}'

  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  App\Decorator\ApiCredentialsHttpClientDecorator:
    decorates: binance_api.client
    arguments:
      - '@App\Decorator\ApiCredentialsHttpClientDecorator.inner'
      - '%app.config.exchange.api_key%'
      - '%app.config.exchange.api_secret%'

  App\Bus\MessageHandler\GenerateBuyOrdersHandler:
    arguments:
      - '@doctrine.orm.entity_manager'
      - !tagged app.order_generator.buy
      - '@Psr\Log\LoggerInterface'

  App\OrderGenerator\LimitLadderBuyOrderGenerator:
    arguments:
      - '@App\Component\ExchangePriceFormatter'
      - '@doctrine.orm.entity_manager'
      - '@Psr\Log\LoggerInterface'
      - '%app.config.exchange.ladder_size%'
    tags:
      - { name: 'app.order_generator.buy', priority: 10 }

  App\OrderGenerator\LimitBuyOrderGenerator:
    tags:
      - { name: 'app.order_generator.buy', priority: 0 }
