App\Model\ExchangeOcoOrder:
  type: entity
  table: exchange_oco_order
  repositoryClass: App\Repository\ExchangeOcoOrderRepository
  id:
    orderListId:
      type: integer
      generator:
        strategy: NONE
  indexes:
    eoo_search_query:
      columns:
        - list_order_status
  fields:
    symbol:
      type: string
      nullable: false
    side:
      type: string
      nullable: false
    stopLimitTimeInForce:
      type: string
      nullable: true
    quantity:
      type: decimal
      precision: 27
      scale: 18
      nullable: false
    price:
      type: decimal
      precision: 27
      scale: 18
      nullable: false
    stopPrice:
      type: decimal
      precision: 27
      scale: 18
      nullable: true
    stopLimitPrice:
      type: decimal
      precision: 27
      scale: 18
      nullable: true
    listStatusType:
      type: string
      nullable: true
    recvWindow:
      type: integer
      nullable: true
    listOrderStatus:
      type: string
      nullable: true
    updatedAt:
      type: bigint
      nullable: true
  manyToOne:
    trade:
      targetEntity: Trade
      nullable: false
      joinColumn:
        name: trade_id
        referencedColumnName: id
        onDelete: CASCADE
    takeProfit:
      targetEntity: TakeProfit
      nullable: false
      joinColumn:
        name: take_profit_id
        referencedColumnName: id
        onDelete: CASCADE


