App\Model\ExchangeOrder:
  type: entity
  table: exchange_order
  repositoryClass: App\Repository\ExchangeOrderRepository
  id:
    orderId:
      type: integer
      generator:
        strategy: NONE
  indexes:
    idx_sdx1:
      columns:
        - status
  fields:
    symbol:
      type: string
      nullable: false
    side:
      type: string
      nullable: false
    type:
      type: string
      nullable: false
    timeInForce:
      type: string
      nullable: true
    quantity:
      type: decimal
      precision: 27
      scale: 18
      nullable: false
    price:
      type: decimal
      precision: 27
      scale: 18
      nullable: false
    stopPrice:
      type: decimal
      precision: 27
      scale: 18
      nullable: true
    icebergQty:
      type: decimal
      precision: 27
      scale: 18
      nullable: true
    newOrderRespType:
      type: string
      nullable: true
    recvWindow:
      type: integer
      nullable: true
    status:
      type: string
      nullable: true
    filledQuantity:
      type: decimal
      precision: 27
      scale: 18
      nullable: true
    filledQuoteQuantity:
      type: decimal
      precision: 27
      scale: 18
      nullable: true
    updatedAt:
      type: bigint
      nullable: true
  manyToOne:
    trade:
      targetEntity: Trade
      nullable: false
      joinColumn:
        name: trade_id
        referencedColumnName: id
        onDelete: CASCADE
    takeProfit:
      targetEntity: TakeProfit
      nullable: true
      joinColumn:
        name: take_profit_id
        referencedColumnName: id
        onDelete: CASCADE
  oneToOne:
    stoploss:
      targetEntity: StopLoss
      inversedBy: order
      nullable: true
      joinColumn:
        name: stoploss_id
        referencedColumnName: id
        onDelete: CASCADE
