App\Model\SymbolFilter:
  type: entity
  repositoryClass: App\Repository\SymbolFilterRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  uniqueConstraints:
    - name: idx_unique
      columns:
        - symbol
        - filter
  fields:
    filter:
      type: string
      nullable: false
    parameters:
      type: json_array
      nullable: false
  manyToOne:
    symbol:
      targetEntity: Symbol
      joinColumn:
        name: symbol
        referencedColumnName: symbol
        onDelete: CASCADE
