App\Model\SymbolFilter:
  type: entity
  repositoryClass: App\Repository\SymbolFilterRepository
  id:
    id:
      type: integer
      generator:
        strategy: IDENTITY
  uniqueConstraints:
    - name: idx_unique
      columns:
        - symbol
        - filter_type
  fields:
    filterType:
      type: string
      nullable: false
    parameters:
      type: json
      nullable: false
  manyToOne:
    symbol:
      targetEntity: Symbol
      joinColumn:
        name: symbol
        referencedColumnName: symbol
        onDelete: CASCADE
