App\Model\TakeProfit:
  type: entity
  repositoryClass: App\Repository\TakeProfitRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    percentage:
      type: decimal
      precision: 3
      scale: 0
      nullable: true
  manyToOne:
    trade:
      targetEntity: Trade
      joinColumn:
        name: trade_id
        referencedColumnName: id
        onDelete: CASCADE
