App\Model\Trade:
  type: entity
  repositoryClass: App\Repository\TradeRepository
  id:
    id:
      type: integer
      generator:
        strategy: IDENTITY
  fields:
    symbol:
      type: string
      length: 50
    stoploss:
      type: decimal
      precision: 27
      scale: 18
      nullable: true
    quantity:
      type: decimal
      precision: 27
      scale: 18
    entryLow:
      type: decimal
      precision: 27
      scale: 18
      nullable: false
    entryHigh:
      type: decimal
      precision: 27
      scale: 18
      nullable: true
    active:
      type: boolean
      default: false
  oneToMany:
    takeProfits:
      targetEntity: TakeProfit
      mappedBy: trade
      cascade: ["persist", "merge"]
    orders:
      targetEntity: ExchangeOrder
      mappedBy: trade
      cascade: ["persist", "merge"]
