App\Model\Trade:
  type: entity
  repositoryClass: App\Repository\TradeRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    symbol:
      type: string
      length: 50
    quantity:
      type: decimal
      precision: 27
      scale: 18
    entryLow:
      type: decimal
      precision: 27
      scale: 18
      nullable: false
    entryHigh:
      type: decimal
      precision: 27
      scale: 18
      nullable: true
  oneToOne:
    stoploss:
      targetEntity: StopLoss
      cascade: ["persist", "merge"]
  oneToMany:
    takeProfits:
      targetEntity: TakeProfit
      mappedBy: trade
      cascade: ["persist", "merge"]
