on: push
name: Lint, test, build & deploy the code
jobs:
  build_frontend_test:
    name: Build the testing frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build.frontend.test
        uses: actions/docker/cli@master
        with:
          args: build -f .docker/frontend/Dockerfile.test -t ci-frontend-${{ github.sha }}:latest .

  build_backend_test:
    name: Build the testing backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build.backend.test
        uses: actions/docker/cli@master
        with:
          args: build -f .docker/backend/Dockerfile.test -t ci-frontend-${{ github.sha }}:latest .

  test_backend:
    name: Test the PHP code
    runs-on: ubuntu-latest
    needs: build_backend_test
    steps:
      - uses: actions/checkout@master
      - name: build.backend.test
        uses: actions/docker/cli@master
        with:
          args: build -f .docker/backend/Dockerfile.test -t ci-backend-${{ github.sha }}:latest .

  test_frontend:
    name: Test the JS code
    runs-on: ubuntu-latest
    needs: build_frontend_test
    steps:
      - uses: actions/checkout@master
      - name: build.frontend.test
        uses: actions/docker/cli@master
        with:
          args: build -f .docker/frontend/Dockerfile.test -t ci-frontend-${{ github.sha }}:latest .

  filter_tag:
    name: Only continue when push is of type tag
    runs-on: ubuntu-latest
    needs:
      - test_frontend
      - test_backend
    steps:
      - uses: actions/checkout@master
      - name: filter.tag
        uses: actions/bin/filter@master
        with:
          args: tag

  build_backend_production:
    name: Build the final production image for the backend
    runs-on: ubuntu-latest
    needs: filter_tag
    steps:
      - uses: actions/checkout@master
      - name: build.backend.production
        uses: actions/docker/cli@master
        with:
          args: build -f .docker/frontend/Dockerfile -t smarttrademanager/backend:latest .

  build_frontend_production:
    name: Build the final production image for the frontend
    runs-on: ubuntu-latest
    needs: filter_tag
    steps:
      - uses: actions/checkout@master
      - name: build.frontend.production
        uses: actions/docker/cli@master
        with:
          args: build -f .docker/frontend/Dockerfile -t smarttrademanager/frontend:latest .
