# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on: push
name: Lint, test, build & deploy the code
jobs:
  build_frontend_test:
    name: Build & test the frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build.frontend.test
        uses: actions/docker/cli@master
        with:
          args: build -f .docker/frontend/Dockerfile.test -t ci-frontend-${{ github.sha }}:latest .
      - name: build.frontend.test
        uses: actions/docker/cli@master
        with:
          args: run ci-frontend-${{ github.sha }}:latest

  build_backend_test:
    name: Build & test the backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build.backend.test
        uses: actions/docker/cli@master
        with:
          args: build -f .docker/backend/Dockerfile.test -t ci-backend-${{ github.sha }}:latest .
      - name: build.backend.test
        uses: actions/docker/cli@master
        with:
          args: run ci-backend-${{ github.sha }}:latest

  login_docker_registry:
    name: Login on the Github package registry
    runs-on: ubuntu-latest
    if: github.event_name == 'tag'
    steps:
      - uses: actions/docker/login@master
        env:
          DOCKER_REGISTRY_URL: docker.pkg.github.com
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  build_backend_production:
    name: Build the final production image for the backend
    runs-on: ubuntu-latest
    if: github.event_name == 'tag'
    needs: build_frontend_test
    steps:
      - uses: actions/checkout@master
      - name: build.backend.production
        uses: actions/docker/cli@master
        with:
          args: build -f .docker/frontend/Dockerfile -t backend .
      - uses: actions/docker/tag@master
        args: backend docker.pkg.github.com/jorijn/smart-trade-manager/backend

  build_frontend_production:
    name: Build the final production image for the frontend
    runs-on: ubuntu-latest
    if: github.event_name == 'tag'
    needs: build_frontend_test
    steps:
      - uses: actions/checkout@master
      - name: build.frontend.production
        uses: actions/docker/cli@master
        with:
          args: build -f .docker/frontend/Dockerfile -t frontend .
      - uses: actions/docker/tag@master
        args: frontend docker.pkg.github.com/jorijn/smart-trade-manager/frontend
